import type { Listing } from '@/lib/types';

export function createListing(overrides: Partial<Listing> = {}): Listing {
  return {
    id: 'listing-1',
    source: 'test-source',
    url: 'https://example.com/listing-1',
    title: 'Test Listing',
    price: 10000,
    acres: 10,
    price_per_acre: 1000,
    state: 'Missouri',
    county: 'Shannon',
    city: 'Eminence',
    description: 'Wooded parcel',
    has_trees: true,
    has_road_access: true,
    has_water: false,
    owner_financing: false,
    in_floodplain: false,
    is_duplicate: false,
    motivated_seller: false,
    enriched: false,
    notified: false,
    price_reduced: false,
    is_down_payment: false,
    latitude: 37.15,
    longitude: -91.37,
    flood_zone: null,
    elevation_ft: null,
    road_distance_m: null,
    water_distance_m: null,
    nearest_town: null,
    town_distance_m: null,
    score: 75,
    hoa_risk: 'unknown',
    hoa_annual_fee: null,
    hoa_flags: null,
    original_price: null,
    full_price: null,
    price_drop_pct: null,
    owner_state: null,
    zoning: null,
    parcel_source: null,
    assessed_value: null,
    canonical_id: null,
    source_aliases: null,
    days_on_market: 0,
    drive_hours: null,
    nearest_major_city: null,
    est_annual_lease: null,
    status: 'active',
    first_seen: null,
    last_seen: null,
    gone_since: null,
    raw_data: null,
    ...overrides,
  };
}
